### ISSUE TITLE
Music not resetting after dying during level/boss clear fanfare on SA-1.

### ISSUE THREAD

**Issue by nambona890** [kkevinm/retry-system#22]
I'm using AddMusicK 1.0.8, the newest release of this Retry System, and SA-1 Pack v1.40. When dying during the boss clear fanfare, the music doesn't reset to the default when respawning. I've attempted to move the AddMusicK freeram to BW-RAM just in case (in both the Retry System and AddMusicK), though there's no change.

**Comment by kkevinm** [comment]
I've tested this with the same setup (AMK 1.0.8, SA-1 1.40, dying after the boss clear starts playing) and the music resets just fine when respawning. My guess is that something else you have in the boss level or some other patch is causing this issue?

**Comment by nambona890** [comment]
Looking closer, the only thing I can think of that could be conflicting is the [Minimalist Course Clear patch](https://www.smwcentral.net/?p=section&a=details&id=18279). The fixes in that patch relating to Reznor can affect $13C6, which is used in the "in_level.asm" to help with Kaizo Traps.

**Comment by kkevinm** [comment]
Okay, I'll give it a look/test.

**Comment by kkevinm** [comment]
Sorry for the wait, I got to test the patch now and this is what I got:
- When messing around with it, I got the patch to show the scorecard immediately after beating Reznor. Dying while the scorecard is up causes the music to not restart as you mentioned, but also if you stay alive the walk never stops and you're softlocked, so I think I found a bug with the patch more than anything else.
- In other cases, with or without the scorecard or with or without the sprite freeze it seems to work fine, so I'm not sure what's going on here.
In any case, I guess you can try to change this line in `retry_config/code/in_level.asm` from `lda $13C6|!addr : bne .force_reset` to `lda $13C6|!addr : ora $1493|!addr : bne .force_reset`.

**Comment by nambona890** [comment]
Unfortunately, testing it with the Big Boo Boss hasn't worked. There may be something in this part of the disassembly that is screwing with it.
`GOAL:		    DEC $13C6|!Base2        ; prevent Mario from walking at the level end
		    LDA #$FF                ; \ set goal
		    STA $1493|!Base2        ; /
		    LDA #!Music             ; \ set ending music
		    STA $1DFB|!Base2        ; /
                    RTS                     ; return`

**Comment by nambona890** [comment]
Looking in the debugger, it's definitely running the code that's in .force_reset, but it doesn't seem to be doing any noticeable thing to the music.

**Comment by kkevinm** [comment]
Mh again, the boo boss also works for me. To be sure, what settings are you using in the minimalist patch?

**Comment by nambona890** [comment]
```
!enable_scorecard = 1 ; 1 will enable the "COURSE CLEAR" text
                      ; along with getting points for the remaining time
                      ; when disabled, layer 3 images will not be overwritten


!enable_circle = 1       ; 1 will enable the zooming circle window effect
                         
!enable_circle_sound = 0 ; you may want to disable this if you disabled the above

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;

!CircleSFX = $00      ; What sound effect plays if the circle is enabled

!BossClear = $03      ; What music plays after beating a boss

!time_after_peace = $30 ; how many frames it'll take for the level to end after Mario 
                        ; shows his "peace" pose. used only if the circle is disabled

!BossWait = $A0       ; how many frames it'll take for the level to end after Mario
                      ; Beats a boss

!FreezeSprites = $00  ; Whether you want to freeze sprites or not after you beat a boss

;; 
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
```

**Comment by kkevinm** [comment]
Yeah, same settings, music resets fine... Actually I have an idea, did you change Addmusic's tweaks.asm file? If so, can you post here the defines you have?

**Comment by nambona890** [comment]
Here's the defines for the global songs, which are the only ones I've changed.
```
!Miss		= #$01			; If you've changed list.txt and plan on using the original SMW songs
!GameOver	= #$02			; change these constants to whatever they are in list.txt
!BossClear	= #$03			; For example, if you changed the "Stage Clear" music to be number 9,
!StageClear	= #$00			; Then you'd change "!StageClear = #$04" to "!StageClear = #$09".
!Starman	= #$05
!PSwitch	= #$00
!Keyhole	= #$07
!IrisOut	= #$00
!BonusEnd	= #$09
```

**Comment by kkevinm** [comment]
Ok yeah as I thought this is actually a bug with AddmusicK: when you change some global songs to 0, weird effects may happen (usually with stage/boss clear, keyhole or iris out). AMK's code checks for these song numbers to do certain stuff so if it's 0 it may result in unintended effects like in this case.
To fix it, open AMK's patch.asm and remove these lines:
```
	CMP !IrisOut
	BEQ ++
```
```
	CMP !IrisOut
	BEQ LevelEndMusicChange
```
```
	CMP !IrisOut
	BEQ Okay
```
(basically all parts with CMP !IrisOut : BEQ something).

**Comment by nambona890** [comment]
Okay, so at first it didn't work when just commenting out the stuff relating to comparing !IrisOut and !StageClear, but then I undid that fix you suggested to in_level.asm, and now it finally works. Thank you a huge amount for the help.
