### ISSUE TITLE
Prompt box appearance is broken with custom text position

### ISSUE THREAD

**Issue by AmperSam-git** [kkevinm/retry-system#67]
If you re-enable the prompt box when there's alternative `!text_x_pos` and `!text_y_pos` values set it borks:

![RHRv5_001](https://github.com/kkevinm/retry-system/assets/81581391/7acfa186-4629-4165-9c0a-ed4282d28c39)

Might be worthwhile overriding any user-set values in favour of hardcoded values when `!no_prompt_box = 0` :)

**Comment by kkevinm** [comment]
tru
