### ISSUE TITLE
Way to reset other status (like reverse gravity) with retry system?

### ISSUE THREAD

**Issue by exedriver** [kkevinm/retry-system#80]
Hey Kevin,

first of all: Thank you very much for your great retry system! I'm using it with the RHR baserom and general, it works like a dream :)

I have one specific question (and to add: I'm just a LM beginner):

I want to use the reverse gravity patch from SMWC (https://www.smwcentral.net/?p=section&a=details&id=19012). However, it seems like to collide with with the retry systems, as after retry, the last "gravity status" is still active and will not be reset. Another user has also mentioned this in the comment section of the reverse gravity patch (see https://smwc.me/s/19012/49005). 

So is there any possibility to reset this gravity status after retry? I've checked the retry_config folder but wasn't able to find any suitable place (as mentioned above, I'm relativly fresh to Lunar Magic).

Thank you very much for your help :)

**Comment by kkevinm** [comment]
Hey, if you want to do that you'd just need to reset the reverse gravity ram (STZ \<address\>) in UberASM init and insert the uberasm in all the levels that use the reverse gravity where you respawn with Retry.
A more handy way to do the same thing in a single place is to add the STZ code in Retry's "retry_config/extra.asm" file, under the "reset:" label: that way the address is reset automatically on every death or when loading the level from the Overworld.

**Comment by exedriver** [comment]
> Hey, if you want to do that you'd just need to reset the reverse gravity ram (STZ <address>) in UberASM init and insert the uberasm in all the levels that use the reverse gravity where you respawn with Retry. A more handy way to do the same thing in a single place is to add the STZ code in Retry's "retry_config/extra.asm" file, under the "reset:" label: that way the address is reset automatically on every death or when loading the level from the Overworld.

Oh man - I'm so blind :D The "reset" function is pretty well described - sorry I didn't find it on my own and thanks for your fast answer :)

So I've copied the syntax from the death-part in the extra.asm, but it doesn't work:

```
reset:
    ; Feel free to put your code here.
    stz $90D4B4|!addr
    rts
```

Results in: `Unknown command. [stz $90D4B4|$0000]`

The addresses in the death-part are all only 4 characters long, the one given from the reverse gravity part 6 chars, so I guess it's related to it. Do you know how I need to write the address here? Or do I need to initialize the address somewhere before using it?

**Comment by kkevinm** [comment]
For long addresses (3 bytes long) you can use LDA #$00 : STA ... instead of STZ, but the issue here is that you're trying to write to a ROM location which you can't change. The address to reset should be this "!reversed = $60" so do STZ $60 (or whatever address you have in the file, if you changed it). If this doesn't work try also calling the gravity code with JSL $90D4B4 (I'm assuming that's what the address you were using is) after doing the STZ.

**Comment by exedriver** [comment]
> For long addresses (3 bytes long) you can use LDA #$00 : STA ... instead of STZ, but the issue here is that you're trying to write to a ROM location which you can't change. The address to reset should be this "!reversed = $60" so do STZ $60 (or whatever address you have in the file, if you changed it). If this doesn't work try also calling the gravity code with JSL $90D4B4 (I'm assuming that's what the address you were using is) after doing the STZ.

`STZ $60` does the trick - thank you soooo much!
