### ISSUE TITLE
Disabling prompt freeze causes a relative branch error on insert

### ISSUE THREAD

**Issue by AmperSam-git** [kkevinm/retry-system#82]
Setting the `!prompt_freeze = 0` causes a relative branch error: 

`s:/temp/retry_test/uberasmtool/retry_config/code/in_level.asm:184 (called from s:/temp/retry_test/uberasmtool/asm/work/library.asm:2): error: (E5037): Relative branch out of bounds. (Distance is 133). [beq ..instant]`

Tested with a clean rom and UberASMTool 2.0

**Comment by kkevinm** [comment]
Did you test it with the latest commit version? I had fixed a similar branching error in b50b0ad.

**Comment by AmperSam-git** [comment]
Ah no, it's with release version. Fixed on main.

**Comment by kkevinm** [comment]
Oh yeah, sorry I wanted to do a new release with some additional fixes but I didn't have the time, maybe I should just do a smaller release since it's an annoying issue 😅
