### ISSUE TITLE
Use UberASM Tool 2.0's new end-of-frame code system instead of hijacking the vanilla end-of-frame routine

### ISSUE THREAD

**Issue by nambona890** [kkevinm/retry-system#88]

**Comment by kkevinm** [comment]
I'll look into it, although I'd have to test all the stuff that uses it and anyway I'd like to keep it compatible with older UberASM Tool versions, but maybe I can add a setting to avoid adding all the level end frame routines and stuff in the ROM if wanted.

**Comment by nambona890** [comment]
I've made a prototype for a hybrid that would account for both <2.0 and 2.0+.
Unfortunately there's a bizarre bug where the first frame of the prompt's RETRY text popping up has all OAM tiles be 8x8.
I haven't tested this fully.
[retry-system-uberasm2-beta1.zip](https://github.com/user-attachments/files/17001346/retry-system-uberasm2-beta1.zip)
![retrypp-20240914-163253](https://github.com/user-attachments/assets/dd87f71a-80cf-4802-81b2-393ab076de34)

**Comment by kkevinm** [comment]
See https://github.com/kkevinm/retry-system/pull/89#issuecomment-2532946183
